# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

# run once at startup
exec-once = ~/.config/hypr/hyprland/scripts/kanshi_dynamic.sh

# polling loop (reliable fallback)
exec-once = while true; do ~/.config/hypr/hyprland/scripts/kanshi_dynamic.sh; sleep 2; done
